'use strict';

var ESO_FACTS = [
                 "that most of the Divines were named after Arena and Daggerfall beta testers?",
                 "that Arena was originally going to be played entirely in a single arena, hence the rather irrelevant title and original box art?",
                 "that Arena is the only game in the main series in which there are no skills that can be learned?",
                 "that Argonians prefer to call themselves Saxhleel, meaning 'People of the Root' in Jel, their native tongue?",
                 "that the Psijic Order has removed their home isle of Artaeum from the world twice?",
                 "that the continent Atmora, the original homeland of the proto-Nords, is said to be uninhabitable as of the late Third Era?",
                 "that the Ayleid language frequently uses compound words?",
                 "that Ayleid ruins can be found in all of Tamriel except Skyrim, Morrowind and the Summerset Isles?",
                 "that the Ayleid runes on the Knights of the Nine box cover translate to 'By the eternal power of Umaril, the mortal gods shall be cast down?'",
                 "that when a Daedra is banished to Oblivion, its body gradually reforms from the Azure Plasm?",
                 "that The Black Horse Courier, Cyrodiil's only newspaper, is funded by the Elder Council and distributed for free to the population?",
                 "that the Hero of Kvatch was able to obtain the blood of a god?",
                 "that the Corprusarium is a place where people with the Corprus disease are experimented upon?",
                 "that the three Daedric runes on the cover of Morrowind are A S V, which stand for Almalexia, Sotha Sil, and Vivec, respectively?",
                 "that Daedric weapons and armor are made from refined ebony and the magical substances of the lesser minions of Oblivion?",
                 "that Daggerfall is the only main Elder Scrolls game that does not begin with the player somehow imprisoned?",
                 "that Daggerfall is the only main Elder Scrolls game that gives the player multiple choices for the end of its main quest?",
                 "that Dagoth Ur had apparently adopted the views and motivations of Kagrenac?",
                 "that the Dawnguard was originally formed to contain the Jarl of Riften's vampire son sometime in the Second Era?",
                 "that the Skyrim town of Dawnstar was once besieged by Ice Tribes, because Governor Cyril Vinticae foolishly let a traitor infiltrate his court?",
                 "that a variety of diseases can be caught by unlucky travelers in the Iliac Bay region, Vvardenfell, Cyrodiil and Skyrim?",
                 "that dragons are sacred to the Empire, and have aided them in ancient wars?",
                 "that the Elder Scrolls held in the White-Gold Tower mysteriously disappeared in 4E 175?",
                 "that reading Elder Scrolls will result in the reader eventually losing their eyesight?",
                 "that there are 61 different kinds of glyphs on the Elder Scrolls, as well as a star map of the real world southern polar region?",
                 "that the province of Elsweyr was formed by the union of Anequina and Pellitine in 2E 309?",
                 "that you can be crowned Emperor in ESO?",
                 "that there are 187 named NPCs who are essential at one point or another in Oblivion?",
                 "that Eyevea was a part of the Shivering Isles for thousands of years, because Shalidor traded it to Sheogorath for the Folium Discognitum?",
                 "that the First Era lasted 2920 years, the Second Era lasted 897 years, and the Third only lasted 433 years?",
                 "that the Forsworn captured the Reach in 4E 174 and held it until it was retaken by Ulfric Stormcloak in 4E 176?",
                 "that Goldbrand was supposedly wielded by Emperor Titus Mede II in the Battle of the Red Ring of 4E 175 against the Aldmeri Dominion?",
                 "that the Bosmer made a Green Pact with Y'ffre, in return for his patronage and protection, that prohibits their use of any plant matter from Valenwood?",
                 "that the Howling Halls were built from the rubble of the Temple of Kynareth where Pelagius Septim III died?",
                 "that a Dremora wrote about the experience of being conjured in I was Summoned by a Mortal?",
                 "that Imperials were not a distinct race until Redguard?",
                 "that, in Vivec's absence, the Ingenium was used to keep Baar Dau from crashing into Vivec City?",
                 "that the publican at the Inn of Ill Omen will buy your stolen goods?",
                 "that jagga, fermented pig's milk, is popular in Valenwood?",
                 "that the Ka Po' Tun are ancient enemies of the Tsaesci?",
                 "that there are seventeen different types of Khajiit, and which type of Khajiit is born is tied to the Lunar Lattice?",
                 "that the Knahaten Flu, which lasted over four decades, nearly wiped out the whole race of the silver-skinned Kothringi people?",
                 "that the book Kyne's Challenge: A Hunter's Companion makes a reference to Skyrim's giants sending players flying into the sky?",
                 "that the Mages Guild was dissolved after the Oblivion Crisis?",
                 "that marauders in Oblivion are always equipped with swords and heavy armor?",
                 "that the only races in Skyrim that you can't marry are Bosmer and Khajiit?",
                 "that mazte is beer local to Morrowind, brewed from fermented saltrice?",
                 "that the month of Morning Star was not present in Morrowind, most likely omitted by accident?",
                 "that Morrowind is the only game in the main series where the player does not have to fight his way out of a starter dungeon?",
                 "that Morrowind is the only main Elder Scrolls game in which the player cannot fast travel?",
                 "that Morrowind is the first TES game in which the player's stamina regenerates on its own?",
                 "that Necromancy is only illegal in the province of Morrowind?",
                 "that the New Sheoth Graveyard gets a new tombstone with a unique inscription added whenever a citizen of New Sheoth dies?",
                 "that Nirn is the name of the planet on which Tamriel, the continent that hosts most events in The Elder Scrolls games, is located?",
                 "that over 1,000 Non-Player Characters are defined in Morrowind, Oblivion and Skyrim?",
                 "that the Numidium was a giant Dwemer construct powered by the Heart of Lorkhan, and used by Tiber Septim to conquer all of Tamriel?",
                 "that when going through an Oblivion Gate in Oblivion, you're usually going to one of seven random worlds?",
                 "that Oblivion is the first TES game in which the player's magicka regenerates on its own?",
                 "that Orcs were not a playable race until Morrowind but rather just a type of monster?",
                 "that Redguard is the only game in which you do not get to 'create' your character?",
                 "that Sheogorath, the Daedric Prince of Madness, was actually Jyggalag, the Daedric Prince of Order, until the other Daedric Princes cursed him to live as the former?",
                 "that the Shivering Isles is split into two distinct regions: Mania, the lighthearted side of its ruler's madness, and Dementia, the darker side?",
                 "that Skyrim was inhabited by Aldmer and Falmer until they were driven out by Ysgramor and the Nords in the late Merethic Era?",
                 "that most buildings in Skyrim are built partly underground to conserve heat, and are made primarily of stone, with wood used only for support, and roofs of straw above the wood?",
                 "that Skyrim is the first TES game in which the player's health regenerates on its own?",
                 "that the lorebook Those Who Stood At Chalman Keep is based on a battle from the ESO beta, where the game's first Emperor was crowned?",
                 "that the Sload created the Thrassian Plague which caused half of the population of the Iliac Bay, and perhaps even Tamriel, to die out in 1E 2260?",
                 "that citizens of Black Marsh travel via an expressway formed within the roots of the Hist trees?",
                 "that the Empire had a Tsaesci ruler for over four hundred years during the Second Era?",
                 "that Nirn's two moons, Masser and Secunda, vanished from 4E 98 until 4E 100, an event that is now called the Void Nights?",
                 "that the White-Gold Concordat was signed in 4E 175, banning the worship of Talos within the Empire?",
                 "that the continent of Yokuda, the original home of the Redguards, sunk around 1E 792?"

                 ];


module.exports = ESO_FACTS;
